sonar.projectKey=api-tareas-devsecops
sonar.projectName=API Tareas DevSecOps
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.sourceEncoding=UTF-8
